name: Trigger 1

on:
  workflow_run:
    workflows:
      - Main
    types:
      - completed

jobs:
  trigger1-job:
    name: Trigger 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: echo workflow
